# TODO: make service names more verbose

services:
  redis:
    image: redis:alpine3.20
    ports:
      - '6379:6379'
    networks:
      - rdnet
    restart: always

  postgres:
    image: postgres:15
    networks:
      - pgnet
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=block-mesh
      - POSTGRES_PORT=5559

  server:
    build:
      context: '../..'
      dockerfile: Dockerfile
      target: development
    ports:
      - '8000:8000'
    networks:
      - pgnet
      - rdnet
    depends_on:
      - postgres
      - redis

  pghero:
    image: ankane/pghero
    container_name: pghero
    ports:
      - '8080:8080'
    networks:
      - pgnet
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/block-mesh
    depends_on:
      - postgres


networks:
  pgnet:
    driver: bridge
  rdnet:
