# https://github.com/LukeMathWalker/zero-to-production/blob/main/.github/workflows/general.yml
name: BUILD
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BLOCKMESH_LOG_ENV: ${{ vars.BLOCKMESH_LOG_ENV }}
#  SCCACHE_GHA_ENABLED: "true"
#  RUSTC_WRAPPER: "sccache"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y  \
            libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf \
            build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUSTC_VERSION }}
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          key: build-sqlx-${{ vars.SQLX_VERSION }}
          cache-all-crates: true
      #      - name: Sccache Action
      #        uses: Mozilla-Actions/sccache-action@v0.0.5
      - name: "Install Cargo Leptos"
        run: |
          cargo install cargo-leptos --version=${{ vars.LEPTOS_VERSION }} --locked
      - name: "Run Cargo Leptos"
        run: |
          export CARGO_TARGET_DIR="target/LEPTOS"
          cargo leptos build --release
      - name: Build
        run: |
          export CARGO_TARGET_DIR="target/REGULAR"
          cargo build --release