name: Release ARM
permissions:
  contents: "write"
on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - "completed"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BLOCKMESH_LOG_ENV: ${{ vars.BLOCKMESH_LOG_ENV }}
  LEPTOS_OUTPUT_NAME: block-mesh-manager
  LEPTOS_SITE_ROOT: target/site
  LEPTOS_SITE_PKG_DIR: pkg
  LEPTOS_SITE_ADDR: 127.0.0.1:8000
  LEPTOS_RELOAD_PORT: 3001
  LEPTOS_LIB_DIR: libs/block-mesh-manager
  LEPTOS_BIN_DIR: libs/block-mesh-manager
  LEPTOS_HASH_FILES: true
  APP_ENVIRONMENT: production
  SENTRY: ${{ secrets.SENTRY }}
  MAPBOX: ${{ secrets.MAPBOX }}
#  SCCACHE_GHA_ENABLED: "true"
#  RUSTC_WRAPPER: "sccache"
jobs:
  get-tag:
    name: "Get Tag From Package Version"
    runs-on:
      group: "arm"
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.PKG_VERSION }}
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown, aarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        with:
          key: release-tag-server-arm
          cache-all-crates: true
      #      - name: Sccache Action
      #        uses: Mozilla-Actions/sccache-action@v0.0.5
      - name: "Get tag"
        id: "pkg-version"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(grep -m 1 '^version' Cargo.toml | sed -e 's/^version\s*=\s*//' | sed -e 's/"//g') >> $GITHUB_OUTPUT
  upload-assets:
    name: "Upload assets to Github releases"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - "get-tag"
    strategy:
      matrix:
        include:
          - target: "aarch64-unknown-linux-gnu"
            os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Download tag"
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.get-tag.outputs.pkg-version }}.txt
      - name: Read value from artifact
        id: read_value
        run: |
          VALUE=$(cat ${{ needs.get-tag.outputs.pkg-version }}.txt)
          echo "value=${VALUE}" >> $GITHUB_ENV
      - name: Create envar
        shell: "bash"
        run: |
          if [ "$value" == "production" ] ; then
            echo "suffix=" >> $GITHUB_ENV
          else
            echo "suffix=staging-" >> $GITHUB_ENV
          fi
      - name: "Check out the repo"
        uses: actions/checkout@v4
      - name: "Install deps"
        run: |
          sudo apt-get update
          sudo apt-get install -y file build-essential pkg-config openssl libssl-dev musl-tools gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown, aarch64-unknown-linux-gnu
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          key: release-upload-${{ matrix.target }}-arm
          cache-all-crates: true
      #      - name: Sccache Action
      #        uses: Mozilla-Actions/sccache-action@v0.0.5
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
      - name: Install zigbuild
        run: |
          cargo install --locked cargo-zigbuild
      - name: "Build CLI"
        run: |
          cargo zigbuild -p blockmesh-cli --release --target ${{ matrix.target }}
          tar acf blockmesh-cli-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/release/blockmesh-cli
      - name: "Build Worker"
        run: |
          cargo build -p block-mesh-manager-worker --release
          tar acf block-mesh-manager-worker-${{ matrix.target }}.tar.gz target/release/block-mesh-manager-worker
      - name: "Copy files to dir"
        run: |
          mkdir -p upload_to
          cp block-mesh-manager-${{ matrix.target }}.tar.gz block-mesh-manager-worker-${{ matrix.target }}.tar.gz blockmesh-cli-${{ matrix.target }}.tar.gz upload_to
      - name: Release
        if: env.value == 'production'
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ needs.get-tag.outputs.pkg-version }}
          files: |
            block-mesh-manager-${{ matrix.target }}.tar.gz
            block-mesh-manager-worker-${{ matrix.target }}.tar.gz
            blockmesh-cli-${{ matrix.target }}.tar.gz
      - name: Upload to R2
        if: env.value == 'staging'
        uses: ryand56/r2-upload-action@latest # Can be any release
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./upload_to
          destination-dir: ${{ needs.get-tag.outputs.pkg-version }} # Can be anything as long as it is an actual path
          output-file-url: 'true' # defaults to true
          multipart-size: 100 # If the file size is greater than the value provided here, then use multipart upload
          max-retries: 5 # The maximum number of retries it takes to upload a multipart chunk until it moves on to the next part
          multipart-concurrent: true # Whether to concurrently upload a multipart chunk
          keep-file-fresh: 'false' # defaults to false
  push-to-registry:
    name: "Push Docker image to Docker Hub"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - "get-tag"
      - "upload-assets"
    runs-on:
      group: "arm"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "blockmesh/blockmesh-cli"
      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v5"
        with:
          context: .
          file: blockmesh-cli.Dockerfile
          push: true
          tags: blockmesh/blockmesh-cli:${ env.suffix }latest-arm64,blockmesh/blockmesh-cli:${ env.suffix }v${{ needs.get-tag.outputs.pkg-version }}
          labels: ${{ steps.meta.outputs.labels }}
# https://codingpackets.com/blog/rust-binary-and-docker-releases-using-github-actions/