name: Release
permissions:
  contents: "write"
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BLOCKMESH_LOG_ENV: ${{ vars.BLOCKMESH_LOG_ENV }}
  LEPTOS_OUTPUT_NAME: block-mesh-manager
  LEPTOS_SITE_ROOT: target/site
  LEPTOS_SITE_PKG_DIR: pkg
  LEPTOS_SITE_ADDR: 127.0.0.1:8000
  LEPTOS_RELOAD_PORT: 3001
  LEPTOS_LIB_DIR: libs/block-mesh-manager
  LEPTOS_BIN_DIR: libs/block-mesh-manager
  LEPTOS_HASH_FILES: true
  APP_ENVIRONMENT: production
  SENTRY: ${{ secrets.SENTRY }}
  MAPBOX: ${{ secrets.MAPBOX }}
#  SCCACHE_GHA_ENABLED: "true"
#  RUSTC_WRAPPER: "sccache"
jobs:
  push-to-registry:
    name: "Push Docker image to Docker Hub"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          key: release-push
          cache-all-crates: true
      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "blockmesh/block-mesh-manager"
      - name: "Build and push Docker image"
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: docker/block-mesh-manager.Dockerfile
          push: true
          tags: blockmesh/block-mesh-manager:latest-amd64